In [5]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [63]:
# 1x6 6x1 2x3 y 3x2
arreglo = np.array([1,2,3,9,8,7]) # creamos un array de una dimension
print(arreglo)

# Hacer referencia
numero_par=arreglo[1] #Hacemos referencia al numero 2 que esta en el indice 1
print(numero_par)

[1 2 3 9 8 7]
2


In [8]:
# tablero tiene 2 dimensiones
tablero = np.array([[1,2,3],[4,5,6],[7,8,9],[0,-1,-2]])
print (tablero)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 -1 -2]]


In [13]:
# ejemplos de referencia a elementos de un arreglo bidimensional
n1 = tablero[0][0] #Hacemos referencia al elemento ubicado en la fila 0 y columna 0
print(n1)
n2 = tablero[3][2] #Hacemos referencia al elemento ubicado en la fila 3 y columna 2
print(n2)
n3 = tablero[2][2] #Hacemos referencia al elemento ubicado en la fila 2 y columna 2
print(n3)
# recordar que los indices empiezan en 0

1
-2
9


In [15]:
# Numero de dimensiones, usamos la propiedad ndim para obtener la dimension de un array
print(arreglo.ndim) # 1
print(tablero.ndim) # 2

1
2


In [17]:
# propiedad "shape", nos devuelve el numero de columnas y filas de un array
print(arreglo.shape) # (3,) significa que es un array de 3 elementos
print(tablero.shape) # (4,3) significa que es un array de 4 filas y 3 columnas

(3,)
(4, 3)


In [18]:
# propiedad "size", nos devuelve el numero total de elementos de un array
print(arreglo.size) # 3 elementos
print(tablero.size) # 12 elementos

3
12


In [20]:
# otras funciones utiles
tablero_ceros = np.zeros((8,8),int) # creamos un tablero de 8x8 con ceros
print(tablero_ceros)

tablero_unos = np.ones((8,8),int) # creamos un tablero de 8x8 con unos
print(tablero_unos)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [22]:
# creamos un tablero inicializado a cualquier valor, este caso es 5
tablero_inicializado = np.full((8,8), 5, int)
print(tablero_inicializado)


[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


In [24]:
# arreglo inicializado con valores aleatorios
arreglo_aleatorio = np.random.random((3,3))
print(arreglo_aleatorio)

[[0.22455243 0.03452061 0.12209617]
 [0.74833008 0.23973185 0.14555626]
 [0.10211738 0.29975104 0.81369891]]


In [29]:
# arreglo inicializado con valores aleatorios enteros
# el 1 y 10 son los valores minimo y maximo que puede tomar el numero aleatorio
arreglo_aleatorio_enteros = np.random.randint(1,11,size=(8,8))
print(arreglo_aleatorio_enteros)

[[ 6  3  7  6  4  1  3  9]
 [ 6  8  7  3  2 10  1  8]
 [ 3  5  7  9  8  5  7  4]
 [ 8 10  2  2  1  9  7  2]
 [ 8  3  6  4  6  1  5  8]
 [10  3  3  4  8  2  1  6]
 [10 10  3  4  6  9  3  6]
 [ 8  8  4  8 10  2 10  3]]


In [60]:
# sumar la fila indicada de un arreglo
suma_fila1 = np.sum(arreglo_aleatorio_enteros[7])
suma_fila2 = np.sum(arreglo_aleatorio_enteros[1])

print(suma_fila1)

# summar con un for
suma_fila2_for = 0
for i in range(8): # este for dara 8 vueltas
    suma_fila1_for = 0
    for j in range(8): # este for dara 8 vueltas
        suma_fila1_for += arreglo_aleatorio_enteros[i][j]
    print(f"la suma de la fila {i} es {suma_fila1_for}")

53
la suma de la fila 0 es 39
la suma de la fila 1 es 45
la suma de la fila 2 es 48
la suma de la fila 3 es 41
la suma de la fila 4 es 41
la suma de la fila 5 es 37
la suma de la fila 6 es 51
la suma de la fila 7 es 53


In [68]:
# propiedad "reshape", nos permite redimensionar un array, siempre y cuando la multiplicacion de las 
# dimensiones sea igual al numero total de elementos del array original "arreglo"

# Redimensionamos "arreglo" a una matriz de 6x1
nuevo_arreglo = arreglo.reshape(6,1)
print(nuevo_arreglo)
# Redimensionamos "arreglo" a una matriz de 3x2
nuevo_arreglo2 = arreglo.reshape(3,2)
print(nuevo_arreglo2)

[[1]
 [2]
 [3]
 [9]
 [8]
 [7]]
[[1 2]
 [3 9]
 [8 7]]
