# Creación de Arrays

In [17]:
# Importing the required library
import numpy as np

# Crea un array unidimensional (vector) con 5 elementos enteros de tu elección.
vector = np.array([1, 2, 3, 4, 5])
print("--------Ejercicio 1.1-----------")
print(vector)
# Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("--------Ejercicio 1.2-----------")
print(matriz)
# Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros.
zeros = np.zeros((2, 4), dtype=int)
print("--------Ejercicio 1.3-----------")
print(zeros)
# Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena de unos.
ones = np.ones((3, 2), dtype=int)
print("--------Ejercicio 1.4-----------")
print(ones)
# Utiliza la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10.
randoms = np.random.randint(0, 10, (4, 4))
print("--------Ejercicio 1.5-----------")
print(randoms)

--------Ejercicio 1.1-----------
[1 2 3 4 5]
--------Ejercicio 1.2-----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------Ejercicio 1.3-----------
[[0 0 0 0]
 [0 0 0 0]]
--------Ejercicio 1.4-----------
[[1 1]
 [1 1]
 [1 1]]
--------Ejercicio 1.5-----------
[[1 7 9 5]
 [9 7 5 3]
 [2 8 1 2]
 [2 7 3 5]]


# Acceso a Elementos

In [27]:
# Accede al tercer elemento del vector creado en el paso 1.
print("--------Ejercicio 2.1-----------")
print(f"Vector : {vector}")
print(f"Tercer elemento del vector : {vector[2]}")
# Accede al elemento en la segunda fila y segunda columna de la matriz creada en el paso 1.
print("--------Ejercicio 2.2-----------")
print(f"Matriz : {matriz}")
print(f"Elemento en la segunda fila y segunda columna de la matriz : {matriz[1, 1]}")

--------Ejercicio 2.1-----------
Vector : [1 2 3 4 5]
Tercer elemento del vector : 3
--------Ejercicio 2.2-----------
Matriz : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento en la segunda fila y segunda columna de la matriz : 5


# Propiedades de los Arrays

In [19]:
# Utiliza el atributo ndim para verificar la cantidad de dimensiones de la matriz creada en el paso 1.
num_dimensions = matriz.ndim
print("--------Ejercicio 3.1-----------")
print(f"Cantidad de dimensiones: {num_dimensions}")

# Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 2.
shape = matriz.shape
print("--------Ejercicio 3.2-----------")
print(f"Forma de la matriz: {shape}")

# Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 2.
size = matriz.size
print("--------Ejercicio 3.3-----------")
print(f"Tamaño total de la matriz: {size}")

--------Ejercicio 3.1-----------
Cantidad de dimensiones: 2
--------Ejercicio 3.2-----------
Forma de la matriz: (3, 3)
--------Ejercicio 3.3-----------
Tamaño total de la matriz: 9


# Operaciones Básicas

In [20]:
# Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.
array1 = np.random.randint(0, 10, (2, 2))
array2 = np.random.randint(0, 10, (2, 2))

# Suma de los dos arrays
sum_arrays = np.add(array1, array2)

print("--------Ejercicio 4.1-----------")
print(f"Array 1: \n{array1}")
print(f"Array 2: \n{array2}")
print(f"Suma de los arrays: \n{sum_arrays}")

# Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.
array3 = np.random.randint(0, 10, (3, 2))
array4 = np.random.randint(0, 10, (2, 3))

# Multiplicación de los dos arrays
mul_arrays = np.dot(array3, array4)

print("--------Ejercicio 4.2-----------")
print(f"Array 3: \n{array3}")
print(f"Array 4: \n{array4}")
print(f"Multiplicación de los arrays: \n{mul_arrays}")

# Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2, utilizando tanto la división por elementos como la multiplicación por la inversa.
array5 = np.random.randint(1, 10, (2, 2))  # Avoid zero to prevent division by zero
array6 = np.random.randint(1, 10, (2, 2))  # Avoid zero to prevent division by zero

# Division de los dos arrays por elementos
div_arrays = np.divide(array5, array6)

print("--------Ejercicio 4.3-----------")
print(f"Array 5: \n{array5}")
print(f"Array 6: \n{array6}")
print(f"División de los arrays: \n{div_arrays}")

# Multiplicación por la inversa
inv_array6 = np.linalg.inv(array6)
div_arrays_inv = np.dot(array5, inv_array6)

print(f"Multiplicación por la inversa: \n{div_arrays_inv}")

--------Ejercicio 4.1-----------
Array 1: 
[[9 3]
 [1 2]]
Array 2: 
[[9 1]
 [0 3]]
Suma de los arrays: 
[[18  4]
 [ 1  5]]
--------Ejercicio 4.2-----------
Array 3: 
[[1 7]
 [5 8]
 [9 9]]
Array 4: 
[[9 9 4]
 [8 6 0]]
Multiplicación de los arrays: 
[[ 65  51   4]
 [109  93  20]
 [153 135  36]]
--------Ejercicio 4.3-----------
Array 5: 
[[4 1]
 [5 8]]
Array 6: 
[[1 9]
 [8 3]]
División de los arrays: 
[[4.         0.11111111]
 [0.625      2.66666667]]
Multiplicación por la inversa: 
[[-0.05797101  0.50724638]
 [ 0.71014493  0.53623188]]


# Manipulación de Arrays

In [21]:
# Utiliza la función reshape() para convertir el vector creado en una matriz de tamaño 1x9.
matriz_1x9 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
matriz_reshape = matriz_1x9.reshape(9, 1)
print("--------Ejercicio 5.1-----------")
print(f"matriz 1x9 : {matriz_1x9}")
print(f"matriz reshape : {matriz_reshape}")

# Utiliza la función flatten() para convertir la matriz creada en el paso 2 en un vector unidimensional.
flattened_matriz = matriz.flatten()
print("--------Ejercicio 5.2-----------")
print(f"matriz : {matriz}")
print(f"matriz flatten : {flattened_matriz}")


--------Ejercicio 5.1-----------
matriz 1x9 : [[1 2 3 4 5 6 7 8 9]]
matriz reshape : [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
--------Ejercicio 5.2-----------
matriz : [[1 2 3]
 [4 5 6]
 [7 8 9]]
matriz flatten : [1 2 3 4 5 6 7 8 9]


# Operaciones Estadísticas

In [22]:
# Calcula la suma de todos los elementos de la matriz creada en el paso 1.
suma_elementos = np.sum(matriz)
print("--------Ejercicio 6.1-----------")
print(f"Matriz: \n{matriz}")
print(f"Suma de todos los elementos: {suma_elementos}")

# Calcula la media de cada fila de la matriz creada en el paso 1.
print("--------Ejercicio 6.2-----------")
print(f"Matriz: \n{matriz}")

# Itera sobre las filas de la matriz
for i, row in enumerate(matriz):
    # Calcula la media de la fila actual
    mean_row = np.mean(row)
    print(f"Media de la fila {i+1}: {mean_row}")

--------Ejercicio 6.1-----------
Matriz: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Suma de todos los elementos: 45
--------Ejercicio 6.2-----------
Matriz: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Media de la fila 1: 2.0
Media de la fila 2: 5.0
Media de la fila 3: 8.0


# Indexación y Rebanado

In [23]:
# Imprime la primera fila de la matriz creada en el paso 1.
primer_fila = matriz[0]
print("--------Ejercicio 7.1-----------")
print(f"Matriz: \n{matriz}")
print(f"Primera fila: {primer_fila}")

# Imprime las primeras dos columnas de la matriz creada en el paso 2.
primeras_dos_columnas = matriz[:, :2]
print("--------Ejercicio 7.2-----------")
print(f"Matriz: \n{matriz}")
print(f"Primeras dos columnas: \n{primeras_dos_columnas}")

--------Ejercicio 7.1-----------
Matriz: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Primera fila: [1 2 3]
--------Ejercicio 7.2-----------
Matriz: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Primeras dos columnas: 
[[1 2]
 [4 5]
 [7 8]]


# Ejercicio Adicional

In [24]:
# Define una matriz de tamaño 4x4 con valores aleatorios.
additional_array = np.random.rand(4, 4)

print("--------Ejercicio 8.1-----------")
print(f"Matriz aleatoria: \n{additional_array}")

# Escribe un código para encontrar el valor máximo y mínimo de la matriz, así como su posición.
max_value = np.max(additional_array)
min_value = np.min(additional_array)
max_position = np.unravel_index(np.argmax(additional_array), additional_array.shape)
min_position = np.unravel_index(np.argmin(additional_array), additional_array.shape)

print("--------Ejercicio 8.2-----------")
print(f"Valor máximo: {max_value}")
print(f"Valor mínimo: {min_value}")
print(f"Posición del valor máximo: {max_position}")
print(f"Posición del valor mínimo: {min_position}")

--------Ejercicio 8.1-----------
Matriz aleatoria: 
[[0.56456283 0.22039269 0.72756238 0.82315907]
 [0.40444419 0.72496854 0.79948906 0.95621806]
 [0.70306473 0.76181725 0.72195304 0.13647904]
 [0.85137753 0.34207667 0.04025008 0.81563558]]
--------Ejercicio 8.2-----------
Valor máximo: 0.9562180550207748
Valor mínimo: 0.040250075847447
Posición del valor máximo: (1, 3)
Posición del valor mínimo: (3, 2)
