In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [2]:
# 1x6 6x1 2x3 y 3x2
arreglo = np.array([1,2,3,9,8,7]) # creamos un array de una dimension
print(arreglo)

# Hacer referencia
numero_par=arreglo[1] #Hacemos referencia al numero 2 que esta en el indice 1
print(numero_par)

[1 2 3 9 8 7]
2


In [3]:
# tablero tiene 2 dimensiones
tablero = np.array([[1,2,3],[4,5,6],[7,8,9],[0,-1,-2]])
print (tablero)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 -1 -2]]


In [4]:
# ejemplos de referencia a elementos de un arreglo bidimensional
n1 = tablero[0][0] #Hacemos referencia al elemento ubicado en la fila 0 y columna 0
print(n1)
n2 = tablero[3][2] #Hacemos referencia al elemento ubicado en la fila 3 y columna 2
print(n2)
n3 = tablero[2][2] #Hacemos referencia al elemento ubicado en la fila 2 y columna 2
print(n3)
# recordar que los indices empiezan en 0

1
-2
9


In [5]:
# Numero de dimensiones, usamos la propiedad ndim para obtener la dimension de un array
print(arreglo.ndim) # 1
print(tablero.ndim) # 2

1
2


In [6]:
# propiedad "shape", nos devuelve el numero de columnas y filas de un array
print(arreglo.shape) # (3,) significa que es un array de 3 elementos
print(tablero.shape) # (4,3) significa que es un array de 4 filas y 3 columnas

(6,)
(4, 3)


In [7]:
# propiedad "size", nos devuelve el numero total de elementos de un array
print(arreglo.size) # 3 elementos
print(tablero.size) # 12 elementos

6
12


In [8]:
# otras funciones utiles
tablero_ceros = np.zeros((8,8),int) # creamos un tablero de 8x8 con ceros
print(tablero_ceros)

tablero_unos = np.ones((8,8),int) # creamos un tablero de 8x8 con unos
print(tablero_unos)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [9]:
# creamos un tablero inicializado a cualquier valor, este caso es 5
tablero_inicializado = np.full((8,8), 5, int)
print(tablero_inicializado)


[[5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5]]


In [10]:
# arreglo inicializado con valores aleatorios
arreglo_aleatorio = np.random.random((3,3))
print(arreglo_aleatorio)

[[0.12429924 0.26769971 0.07569014]
 [0.1451633  0.81357787 0.03830214]
 [0.27200259 0.80080834 0.77728054]]


In [11]:
# arreglo inicializado con valores aleatorios enteros
# el 1 y 10 son los valores minimo y maximo que puede tomar el numero aleatorio
arreglo_aleatorio_enteros = np.random.randint(1,11,size=(8,8))
print(arreglo_aleatorio_enteros)

[[ 3  1  6  6  3  4  3  2]
 [ 9  6  5  9  4  5  1  7]
 [10  6  3  6  2  6  5 10]
 [ 1  8  2  2  4  7  9  5]
 [ 4  8 10  3  1  6  9  1]
 [ 5  7  6  6  7  4  1  3]
 [ 3  2 10  2  5  4  3  3]
 [ 2  2  9  1  5  9  1  4]]


In [12]:
# sumar la fila indicada de un arreglo
suma_fila1 = np.sum(arreglo_aleatorio_enteros[7])
suma_fila2 = np.sum(arreglo_aleatorio_enteros[1])

print(suma_fila1)

# summar con un for
suma_fila2_for = 0
for i in range(8): # este for dara 8 vueltas
    suma_fila1_for = 0
    for j in range(8): # este for dara 8 vueltas
        suma_fila1_for += arreglo_aleatorio_enteros[i][j]
    print(f"la suma de la fila {i} es {suma_fila1_for}")

33
la suma de la fila 0 es 28
la suma de la fila 1 es 46
la suma de la fila 2 es 48
la suma de la fila 3 es 38
la suma de la fila 4 es 42
la suma de la fila 5 es 39
la suma de la fila 6 es 32
la suma de la fila 7 es 33


In [13]:
# propiedad "reshape", nos permite redimensionar un array, siempre y cuando la multiplicacion de las 
# dimensiones sea igual al numero total de elementos del array original "arreglo"

# Redimensionamos "arreglo" a una matriz de 6x1
nuevo_arreglo = arreglo.reshape(6,1)
print(nuevo_arreglo)
# Redimensionamos "arreglo" a una matriz de 3x2
nuevo_arreglo2 = arreglo.reshape(3,2)
print(nuevo_arreglo2)

[[1]
 [2]
 [3]
 [9]
 [8]
 [7]]
[[1 2]
 [3 9]
 [8 7]]


: 